config/routes.rb
Appinfo::Application.routes.draw do
  root :to => 'servers#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

  namespace :admin do
    match '/' => 'admin#index'
    resources :users
  end

  resources :applications
  resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /html|csv/
  resources :token_authentications, :only => [:create, :destroy]
  resources :application_versions
  resources :server_relationships
  resources :server_databases
  resources :databases
  resources :application_families
  resources :application_family_applications
  resources :server_applications
  resource :user, only: [:show]

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false), :defaults => {:format => :json} do
      resources :application_versions do
        collection do
          get :exists
        end
      end
      resources :applications do
        resources :application_versions
        collection do
          get :exists
        end
      end
      resources :servers, :id => /[\w.]+?/  do
        resources :application_versions
        resources :applications
        put :associate_application
        get :has_application
      end
      resources :server_relationships do
        collection do
          get :exists
        end
      end
      resources :server_databases do
        collection do
          get :exists
        end
      end
      resources :databases do
        collection do
          get :exists
        end
      end
      resources :application_families
      resources :application_family_applications do
        collection do
          get :exists
        end
      end
      resources :server_applications do
        collection do
          get :exists
        end
      end
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true), :defaults => {:format => :json} do
      resources :applications, :id => /[\w\d%\-]+?/ do
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :only => [:index, :show], :format => /json|csv|xml|yaml/ do
          resource :application_version
        end
        resources :databases, :id => /[\w\d%\-]+?/
        resources :server_applications, :only => [:index, :show]
      end
      resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/ do
        resources :applications, :id => /[\w\d%\-]+?/  do
          resource :application_version
          resources :server_applications
        end
        resources :server_applications do
          resource :application_version
        end
        resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
          resources :server_databases
        end
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/
        resources :server_relationships
        resources :server_databases
      end
      resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
        resource :application, :id => /[\w\d%\-]+?/
        resources :server_databases, :only => [:index, :show]
      end
      resources :application_families do
        resources :application_family_applications
      end
      resources :application_versions, :only => [:index, :show]
      resources :server_applications, :only => [:index, :show]
      resources :server_databases, :only => [:index, :show]
      resources :server_relationships, :only => [:index, :show]
      resources :application_family_applications, :only => [:index, :show]
    end
  end
end

app/views/menus/_admin.html.erb
<%= link_to t('admin.administration'), admin_path %>

app/views/menus/_footer.html.erb
<div id="footer_menu">
  <ul>
    <li><%= link_to t('api.api_docs'), '/api' %></li>
    <% unless user_signed_in? && User.omniauth_providers && User.omniauth_providers.include?(:auth_man) %>
        <li><%= link_to t('users.local_login'), new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/menus/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('application.name'), root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.role?(:admin) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('admin.administration') %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= render 'menus/admin' %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('general.views') %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to t('applications.show'), applications_path %></li>
            <li><%= link_to t('databases.databases'), databases_path %></li>
            <li><%= link_to t('servers.show'), servers_path %></li>
            <li class="divider"></li>
            <li><%= link_to t('application_families.application_families'), application_families_path %></li>
            <li><%= link_to t('application_family_applications.application_family_applications'), application_family_applications_path %></li>
            <li><%= link_to t('application_versions.application_versions'), application_versions_path %></li>
            <li class="divider"></li>
            <li><%= link_to t('server_applications.server_applications'), server_applications_path %></li>
            <li><%= link_to t('server_databases.server_databases'), server_databases_path %></li>
            <li><%= link_to t('server_relationships.server_relationships'), server_relationships_path %></li>
          </ul>
        </li>
        <li class="divider-vertical"></li>
        <%= render 'menus/my_account', :app_config => APP_CONFIG, :user => current_user, :my_account_path => user_path, :gravatar_url => current_user.gravatar_url(:size => 20) if user_signed_in? %>
        <% unless user_signed_in? %>
          <% if User.omniauth_providers && User.omniauth_providers.include?(:auth_man) %>
            <li><%= link_to(t('users.login'), user_omniauth_authorize_path(:auth_man)) %></li>
          <% else %>
            <li><%= link_to(t('users.login'), new_user_session_path) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>