config/routes.rb
Appinfo::Application.routes.draw do
  root :to => 'servers#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

  namespace :admin do
    match '/' => 'admin#index'
    resources :users
  end

  resources :applications
  resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /html|csv/
  resources :token_authentications, :only => [:create, :destroy]
  resources :application_versions
  resources :server_relationships
  resources :server_databases
  resources :databases
  resources :application_families
  resources :application_family_applications
  resources :server_applications
  resource :user, only: [:show]

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false), :defaults => {:format => :json} do
      resources :application_versions do
        collection do
          get :exists
        end
      end
      resources :applications do
        resources :application_versions
        collection do
          get :exists
        end
      end
      resources :servers, :id => /[\w.]+?/  do
        resources :application_versions
        resources :applications
        put :associate_application
        get :has_application
      end
      resources :server_relationships do
        collection do
          get :exists
        end
      end
      resources :server_databases do
        collection do
          get :exists
        end
      end
      resources :databases do
        collection do
          get :exists
        end
      end
      resources :application_families
      resources :application_family_applications do
        collection do
          get :exists
        end
      end
      resources :server_applications do
        collection do
          get :exists
        end
      end
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true), :defaults => {:format => :json} do
      resources :applications, :id => /[\w\d%\-]+?/ do
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :only => [:index, :show], :format => /json|csv|xml|yaml/ do
          resource :application_version
        end
        resources :databases, :id => /[\w\d%\-]+?/
        resources :server_applications, :only => [:index, :show]
      end
      resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/ do
        resources :applications, :id => /[\w\d%\-]+?/  do
          resource :application_version
          resources :server_applications
        end
        resources :server_applications do
          resource :application_version
        end
        resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
          resources :server_databases
        end
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/
        resources :server_relationships
        resources :server_databases
      end
      resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
        resource :application, :id => /[\w\d%\-]+?/
        resources :server_databases, :only => [:index, :show]
      end
      resources :application_families do
        resources :application_family_applications
      end
      resources :application_versions, :only => [:index, :show]
      resources :server_applications, :only => [:index, :show]
      resources :server_databases, :only => [:index, :show]
      resources :server_relationships, :only => [:index, :show]
      resources :application_family_applications, :only => [:index, :show]
    end
  end
end

app/models/server_relationship.rb
class ServerRelationship < ActiveRecord::Base
  attr_accessible :port, :server_primary_id, :server_secondary_id, :server_primary, :server_secondary, :ignore_active, :active, :description

  belongs_to :server_primary, :foreign_key => :server_primary_id, :class_name => 'Server'
  belongs_to :server_secondary, :foreign_key => :server_secondary_id, :class_name => 'Server'

  validates :server_primary_id, :presence => true
  validates :server_secondary_id, :presence => true

  validates_uniqueness_of :port, :scope => [:server_secondary_id, :server_primary_id]

  before_create :initialize_last_checked
  before_update :initialize_last_checked

  def update_last_checked
    self.last_checked_at = Time.new
    self.active = true
    self.save!
  end

  def is_active?(length = 1.month.ago)
    if self.ignore_active?
      true
    elsif self.last_checked_at < length
      false
    else
      true
    end
  end

  def set_active(active)
    self.active = active
    self.save
  end

  private
  def initialize_last_checked
    self.last_checked_at = Time.new
  end
end

app/controllers/api/v1/server_relationships_controller.rb
class API::V1::ServerRelationshipsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    @server_relationships = ServerRelationship.all

    respond_to do |format|
      format.xml   { render xml:  @server_relationships, :include => [:server_primary, :server_secondary] }
      format.json
    end
  end

  def show
    @server_relationship = ServerRelationship.find(params[:id])
    @server_relationship.update_last_checked if @server_relationship

    respond_to do |format|
      format.json
    end
  end

  def exists
    server_primary    = Server.find_by_name(params[:server_primary])
    server_secondary  = Server.find_by_name(params[:server_secondary])

    @server_relationship = ServerRelationship.find_by_server_primary_id_and_server_secondary_id_and_port(server_primary.id, server_secondary.id, params[:port]) if server_primary && server_secondary && params[:port]
    @server_relationship.update_last_checked if @server_relationship

    respond_to do |format|
      format.json { render json: @server_relationship }
    end
  end

  def create
    server_primary = get_server_by_id_or_name params[:server_relationship][:server_primary]
    server_secondary = get_server_by_id_or_name params[:server_relationship][:server_secondary]

    @server_relationship = ServerRelationship.new(
                                                 :server_primary   => server_primary,
                                                 :server_secondary => server_secondary,
                                                 :port             => params[:server_relationship][:port] ? params[:server_relationship][:port].to_i : nil,
                                                 :description      => params[:server_relationship][:description]
    )

    respond_to do |format|
      if @server_relationship.save
        format.json { render json: @server_relationship, status: :created, location: @server_relationship }
      else
        format.json { render json: @server_relationship.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/api/v2/server_relationships_controller.rb
class API::V2::ServerRelationshipsController < API::APIBaseController
  before_filter :authenticate_user!, :except => [:index, :show]

  swagger_controller :server_relationship, 'Server Relationship Management'

  swagger_api :index do
    summary 'Fetches all Server Relationship items'
    notes 'This lists all the Server Relationships'
    param :path, :server_id, :string, :optional, 'Primary Server Name'
  end

  swagger_api :show do
    summary 'Fetches a single Server Relationship item'
    param :path, :server_id, :string, :required, 'Primary Server Name'
    param :path, :id, :string, :required, 'Server Relationship ID or Secondary Server Name'
    param :query, :port, :integer, :required, 'The destination port'
  end

  swagger_api :create do
    summary 'Creates a new Server Relationship item'
    param :form, :auth_token, :string, :required, "An authorized user's token."
    param :path, :server_id, :string, :required, 'Primary Server Name'
    param :form, 'server_relationship[server_secondary_id]', :string, :required, 'Secondary Server Name'
    param :form, 'server_relationship[port]', :integer, :required, 'The destination port'
    param :form, 'server_relationship[description]', :string, :optional, 'A description of this Server Relationship'
    param :form, 'server_relationship[ignore_active]', :boolean, :optional, 'Whether to ignore the active parameter'
    param :form, 'server_relationship[active]', :boolean, :optional, 'Whether this Database item is active'
  end

  def index
    if params[:server_id]
      @server_relationships = ServerRelationship.find_all_by_server_primary_id!(Server.find(params[:server_id]).id)
    else
      @server_relationships = ServerRelationship.all
    end

    respond_to do |format|
      format.xml   { render xml:  @server_relationships, :include => [:server_primary, :server_secondary] }
      format.json
    end
  end

  def show
    if params[:server_id] && params[:id] && params[:port]
      @server_relationship = ServerRelationship.find_by_server_primary_id_and_server_secondary_id_and_port!(Server.find(params[:server_id]).id, Server.find(params[:id]).id, params[:port])
    else
      @server_relationship = ServerRelationship.find(params[:id])
    end


    respond_to do |format|
      if @server_relationship
        @server_relationship.update_last_checked

        format.json
      else
        raise ActiveRecord::RecordNotFound.new("#{ServerRelationship} not found.")
      end
    end
  end

  def create
    if params[:server_id]
      params[:server_relationship][:server_secondary_id] = Server.find(params[:server_relationship][:server_secondary_id]).id

      @server_relationship = Server.find(params[:server_id]).server_relationships.new(params[:server_relationship])
    end

    respond_to do |format|
      if @server_relationship.save!
        format.json { render json: @server_relationship, status: :created, location: @server_relationship }
      else
        format.json { render json: @server_relationship.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/server_relationships_controller.rb
class ServerRelationshipsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /server_relationships
  def index
    @server_relationships = ServerRelationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.csv  { render csv: @server_relationships, add_methods: [:server_primary, :server_secondary], exclude: [:server_primary_id, :server_secondary_id] }
    end
  end

  # GET /server_relationships/1
  def show
    @server_relationship = ServerRelationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /server_relationships/new
  def new
    @server_relationship = ServerRelationship.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /server_relationships/1/edit
  def edit
    @server_relationship = ServerRelationship.find(params[:id])
  end

  # POST /server_relationships
  def create
    @server_relationship = ServerRelationship.new(params[:server_relationship])

    respond_to do |format|
      if @server_relationship.save
        format.html { redirect_to @server_relationship, notice: 'Server relationship was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /server_relationships/1
  def update
    @server_relationship = ServerRelationship.find(params[:id])

    respond_to do |format|
      if @server_relationship.update_attributes(params[:server_relationship])
        format.html { redirect_to @server_relationship, notice: 'Server relationship was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /server_relationships/1
  def destroy
    @server_relationship = ServerRelationship.find(params[:id])
    @server_relationship.destroy

    respond_to do |format|
      format.html { redirect_to server_relationships_url }
    end
  end
end

app/helpers/server_relationships_helper.rb
module ServerRelationshipsHelper
end

app/views/server_relationships/_form.html.erb
<%= form_for(@server_relationship) do |f| %>
  <% if @server_relationship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server_relationship.errors.count, "error") %> prohibited this server_relationship from being saved:</h2>

      <ul>
      <% @server_relationship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :server_primary %><br />
    <%= f.collection_select :server_primary_id, Server.order(:name),:id,:name %>
  </div>
  <div class="field">
    <%= f.label :server_secondary %><br />
    <%= f.collection_select :server_secondary_id, Server.order(:name),:id,:name %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.number_field :port %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :ignore_active %>
    <%= f.check_box :ignore_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/server_relationships/edit.html.erb
<h1><%= t('general.editing') % "#{@server_relationship.server_primary.name} - #{@server_relationship.server_secondary.name}" %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Show', @server_relationship %> |
<%= link_to 'Back', server_relationships_path %>

app/views/server_relationships/index.html.erb
<h1><%= t('general.listing') % t('server_relationships.server_relationships') %>
  <span class='actions'>
        <% if user_signed_in? %>
          <%= link_to 'New', new_server_relationship_path, :id => 'new_server_link' %>
        <% end  %>
    </span>
</h1>

<table id='index_table' class='data_table'>
  <thead>
    <tr>
      <th><%= t('server_relationships.primary_server') %></th>
      <th><%= t('server_relationships.secondary_server') %></th>
      <th><%= t('server_relationships.port') %></th>
      <th><%= t('general.tables.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @server_relationships.each do |server_relationship| %>
    <tr>
      <td><%= server_relationship.server_primary %></td>
      <td><%= server_relationship.server_secondary %></td>
      <td><%= server_relationship.port %></td>
      <td>
        <%= link_to t('general.show'), server_relationship_path(server_relationship) %>
        <% if user_signed_in? %>
        <%= link_to t('general.edit'), edit_server_relationship_path(server_relationship) %>
        <%= link_to t('general.destroy'), server_relationship, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />
<div>
  <%= t('general.download') %>: <%= link_to t('general.csv'), server_relationships_path(format: 'csv') %>
</div>

app/views/server_relationships/new.html.erb
<h1><%= t('general.new') % t('server_relationships.server_relationship') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to 'Back', server_relationships_path %>

app/views/server_relationships/show.html.erb
<h1><%= t('server_relationships.server_relationship') %></h1>
<div class='model_info'>
  <b><%= t('server_relationships.primary_server') %></b>
  <%= link_to @server_relationship.server_primary, @server_relationship.server_primary %><br/>
  <b><%= t('server_relationships.secondary_server') %></b>
  <%= link_to @server_relationship.server_secondary, @server_relationship.server_secondary %><br/>
  <b><%= t('server_relationships.description') %>:</b>
  <%= @server_relationship.description %><br/>
  <b><%= t('server_relationships.port') %>:</b>
  <%= @server_relationship.port.to_s %><br/>
  <br />
  <b><%= t('general.last_api_check_at') %>:</b>
  <%= @server_relationship.last_checked_at.to_formatted_s(:long_ordinal) %><br/>
  <b><%= t('general.active') %>:</b>
  <%= @server_relationship.active? ? t('general.yes') : t('general.no') %><br/>
  <b><%= t('general.created_on') %>:</b>
  <%= @server_relationship.created_at.to_formatted_s(:long_ordinal) %><br/>
  <b><%= t('general.updated_on') %>:</b>
  <%= @server_relationship.updated_at.to_formatted_s(:long_ordinal) %><br/><br/><br/>
</div>
<br/><br/><br/>

<%= link_to t('general.back'), :back %>
<% if user_signed_in? %>
    | <%= link_to t('general.edit'), edit_server_relationship_path(@server_relationship) %>
<% end %>