config/routes.rb
Appinfo::Application.routes.draw do
  root :to => 'servers#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

  namespace :admin do
    match '/' => 'admin#index'
    resources :users
  end

  resources :applications
  resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /html|csv/
  resources :token_authentications, :only => [:create, :destroy]
  resources :application_versions
  resources :server_relationships
  resources :server_databases
  resources :databases
  resources :application_families
  resources :application_family_applications
  resources :server_applications
  resource :user, only: [:show]

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false), :defaults => {:format => :json} do
      resources :application_versions do
        collection do
          get :exists
        end
      end
      resources :applications do
        resources :application_versions
        collection do
          get :exists
        end
      end
      resources :servers, :id => /[\w.]+?/  do
        resources :application_versions
        resources :applications
        put :associate_application
        get :has_application
      end
      resources :server_relationships do
        collection do
          get :exists
        end
      end
      resources :server_databases do
        collection do
          get :exists
        end
      end
      resources :databases do
        collection do
          get :exists
        end
      end
      resources :application_families
      resources :application_family_applications do
        collection do
          get :exists
        end
      end
      resources :server_applications do
        collection do
          get :exists
        end
      end
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true), :defaults => {:format => :json} do
      resources :applications, :id => /[\w\d%\-]+?/ do
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :only => [:index, :show], :format => /json|csv|xml|yaml/ do
          resource :application_version
        end
        resources :databases, :id => /[\w\d%\-]+?/
        resources :server_applications, :only => [:index, :show]
      end
      resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/ do
        resources :applications, :id => /[\w\d%\-]+?/  do
          resource :application_version
          resources :server_applications
        end
        resources :server_applications do
          resource :application_version
        end
        resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
          resources :server_databases
        end
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/
        resources :server_relationships
        resources :server_databases
      end
      resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
        resource :application, :id => /[\w\d%\-]+?/
        resources :server_databases, :only => [:index, :show]
      end
      resources :application_families do
        resources :application_family_applications
      end
      resources :application_versions, :only => [:index, :show]
      resources :server_applications, :only => [:index, :show]
      resources :server_databases, :only => [:index, :show]
      resources :server_relationships, :only => [:index, :show]
      resources :application_family_applications, :only => [:index, :show]
    end
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name, :app_type, :sends_emails, :path, :version_command, :major_application, :ignore_active, :active, :application_families

  validates :name, presence: true,
                   uniqueness: true

  belongs_to :user

  has_many :application_family_applications, :dependent => :destroy
  has_many :server_applications, :dependent => :destroy

  has_many :servers, through: :server_applications
  has_many :application_families, through: :application_family_applications, :uniq => true

  has_many :databases

  before_save :fix_case
  before_save :replace_string
  before_create :initialize_last_checked
  before_update :initialize_last_checked

  extend FriendlyId
  friendly_id :name

  def to_s
    self.name
  end

  def update_last_checked
    self.last_checked_at = Time.new
    self.active = true
    self.save!
  end

  def is_active?(length = 1.month.ago)
    if self.ignore_active?
      true
    elsif self.last_checked_at < length
      false
    else
      true
    end
  end

  def set_active(active)
    self.active = active
    self.save
  end

  private
  def initialize_last_checked
    self.last_checked_at = Time.new
  end

  def fix_case
    if self.app_type
      self.app_type = self.app_type.downcase
    end
  end

  def replace_string
    if self.version_command
      self.attributes.each_pair do |name, value|
        self.version_command = self.version_command.gsub("%#{name}%", value.to_s)
      end
    end
  end
end

app/controllers/api/v1/applications_controller.rb
class API::V1::ApplicationsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /applications
  # GET /applications.json
  def index
    if params[:server_id]
      @applications = Server.find(params[:server_id]).applications
    else
      @applications = Application.all
    end


    respond_to do |format|
      format.xml   { render xml:  @applications }
      format.json
    end
  end

  # GET /applications/1.json
  def show
    if params[:name] && params[:app_type] && params[:version]
      conditions = {
          :name => params[:name],
          :app_type => params[:app_type],
          :version => params[:version]
      }

      @application = Application.first(:conditions => conditions)
    else
      @application = Application.find_by_id(params[:id])
      @application ||= Application.find_by_name(params[:id])
    end

    @application.update_last_checked if @application


    respond_to do |format|
      format.xml   { render xml:  @application }
      format.json
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed New Action - #{request.url}"

    respond_to do |format|
      format.xml   { render xml:  @application }
      format.json  { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed Edit Action - #{request.url}"
    logger.debug "#{current_user.email} @ #{request.remote_ip} - Edited #{@application.name}"
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = current_user.applications.new(params[:application])

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed Create Action - #{request.url}"
    logger.debug "#{current_user.email} @ #{request.remote_ip} - Created #{@application.name}"

    respond_to do |format|
      if @application.save
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Creation of #{@application.name} succeeded"

        format.xml { render xml: @application, status: :created, location: @application }
        format.json { render json: @application, status: :created, location: @application }
      else
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Creation of #{@application.name} failed"

        format.xml { render xml: @application.errors, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed Update Action - #{request.url}"
    logger.debug "#{current_user.email} @ #{request.remote_ip} - Update #{@application.name}"

    respond_to do |format|
      if @application.update_attributes(params[:application])
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Update of #{@application.name} succeeded"

        format.xml { head :no_content }
        format.json { head :no_content }
      else
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Update of #{@application.name} failed"

        format.xml { render xml: @application.errors, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed Destroy Action - #{request.url}"
    logger.debug "#{current_user.email} @ #{request.remote_ip} - Destroy #{@application.name}"

    @application.destroy

    respond_to do |format|
      format.xml { head :no_content }
      format.json { head :no_content }
    end
  end

  def exists
    application = Application.find_by_id(params[:application])
    application ||= Application.find_by_name(params[:application])

    application.update_last_checked if application

    respond_to do |format|
      format.json { render json: application }
    end
  end
end

app/controllers/api/v2/applications_controller.rb
class API::V2::ApplicationsController < API::APIBaseController
  before_filter :authenticate_user!, :except => [:index, :show]

  swagger_controller :application, 'Application Management'

  swagger_api :index do
    summary 'Fetches all Application items'
    notes 'This lists all the Versions'
    param :path, :server_id, :string, :optional, 'Server Name, fetch all Applications for the indicated Server'
  end

  swagger_api :show do
    summary 'Fetches a single Application item'
    param :path, :id, :string, :required, 'Application Name or Server Name'
    param :path, :application_id, :string, :optional, 'Application Name'
    param :path, :database_id, :string, :optional, 'Database Name'
    param :path, :server_id, :string, :optional, 'Server Name'
  end

  swagger_api :create do
    summary 'Creates a new Application item'
    param :form, :auth_token, :string, :required, "An authorized user's token."
    param :path, :database_id, :string, :required, 'Database Name'
    param :path, :server_id, :string, :required, 'Server Name'
    param :form, 'application[name]', :string, :required, 'Application Name'
    param :form, 'application[app_type]', :string, :optional, 'Application Type'
    param :form, 'application[sends_emails]', :boolean, :optional, 'Wether this Application sends emails.'
    param :form, 'application[path]', :string, :optional, 'The path to the installed Application'
    param :form, 'application[version_command]', :string, :optional, 'Command to check the version of the Application'
    param :form, 'application[major_application]', :boolean, :optional, 'Whether this Application is a major one'
    param :form, 'application[ignore_active]', :boolean, :optional, 'Whether to ignore the active parameter'
    param :form, 'application[active]', :boolean, :optional, 'Whether this Application Family item is active'
  end

  # GET /applications
  # GET /applications.json
  def index
    if params[:server_id]
      @applications = Server.find(params[:server_id]).applications
    elsif params[:application_family_id]
      @applications = ApplicationFamily.find(params[:application_family_id]).applications
    else
      @applications = Application.all
    end

    respond_to do |format|
      format.xml   { render xml:  @applications }
      format.json
    end
  end

  # GET /applications/1.json
  def show
    if params[:database_id]
      database = Database.find(params[:database_id])
      database.update_last_checked
      @application = database.application
    elsif params[:server_id] && params[:id]
      server_application = ServerApplication.find_by_application_id_and_server_id!(Application.find(params[:id]).id, Server.find(params[:server_id]).id)
      server_application.update_last_checked
      @application = server_application.application
    else
      @application = Application.find(params[:id])
    end

    @application.update_last_checked if @application


    respond_to do |format|
      format.xml   { render xml:  @application }
      format.json
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed New Action - #{request.url}"

    respond_to do |format|
      format.xml   { render xml:  @application }
      format.json  { render json: @application }
    end
  end

  # POST /applications
  # POST /applications.json
  def create
    if params[:server_id]
      server = Server.find(params[:server_id])

      @application = server.applications.new(params[:application])
    elsif params[:database_id]
      database = Database.find(params[:database_id])

      @application = database.build_application(params[:application])
    else
      @application = current_user.applications.new(params[:application])
    end

    logger.info "#{current_user.email} @ #{request.remote_ip} - Accessed Create Action - #{request.url}"
    logger.debug "#{current_user.email} @ #{request.remote_ip} - Created #{@application.name}"

    respond_to do |format|
      if @application.save!
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Creation of #{@application.name} succeeded"

        format.xml { render xml: @application, status: :created, location: @application }
        format.json { render json: @application, status: :created, location: @application }
      else
        logger.debug "#{current_user.email} @ #{request.remote_ip} - Creation of #{@application.name} failed"

        format.xml { render xml: @application.errors, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_timezone

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end

  def set_timezone
    Time.zone = current_user.time_zone if current_user
  end

  private
  def get_server_by_id_or_name(server_id_or_name)
    if server_id_or_name =~ /\A[-+]?\d+\z/
      server = Server.find(server_id_or_name.to_i)
    else
      server = Server.find_by_name(server_id_or_name)
    end

    server
  end

  def get_database_by_id_or_name_and_dbms(database_id_or_name_and_dbms)
    if database_id_or_name_and_dbms =~ /\A[-+]?\d+\z/
      database = Database.find(database_id_or_name_and_dbms.to_i)
    else
      database = Database.find_by_name_and_dbms(database_id_or_name_and_dbms[:name], database_id_or_name_and_dbms[:dbms])
    end

    database
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_applications.html.erb
<table id='index_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('general.tables.name') %></th>
    <th><%= t('applications.type') %></th>
    <th><%= t('servers.servers') %></th>
    <% if user_signed_in? %>
        <th><%= t('general.tables.actions') %></th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% applications.each do |application| %>
      <tr>
        <td><%= link_to application.name, application %></td>
        <td><%= application.app_type %></td>
        <td><%= application.servers.count %></td>
        <% if user_signed_in? %>
            <td>
              <%= link_to t('general.edit'), edit_application_path(application) %>
              <%= link_to t('general.destroy'), application, method: :delete, data: { confirm: t('general.are_you_sure') } %>
            </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, t('errors.error')) %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :app_type %><br />
    <%= f.text_field :app_type %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :version_command %><br />
    <%= f.text_area :version_command %>
  </div>
  <div class="field">
    <%= f.label :sends_emails %><br />
    <%= f.check_box :sends_emails %>
  </div>
  <div class="field">
    <%= f.label :major_application %><br />
    <%= f.check_box :major_application %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :ignore_active %>
    <%= f.check_box :ignore_active %>
  </div>
  <div class="field">
    <%= f.label :servers %><br />
    <%= f.select :server_ids, @servers.collect {|x| ["#{x.name}", x.id]}, {}, :multiple => true %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1><%= t('general.editing') % t('applications.applications') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to t('general.show'), @application %> |
<%= link_to t('general.back'), applications_path %>

app/views/applications/index.html.erb
<h1><%= t('general.listing') % t('applications.applications') %>
  <span class='actions'>
        <% if user_signed_in? %>
          <%= link_to 'New', new_application_path(@application), :id => t('applications.new_application_link') %>
        <% end  %>
    </span>
</h1>

<%= render 'applications/applications', :applications => @applications %>

<br />
<br />
<div>
  <%= t('general.download') %>: <%= link_to t('general.csv'), applications_path(format: 'csv') %>
</div>

app/views/applications/new.html.erb
<h1><%= t('general.new') % t('applications.application') %></h1>

<%= render 'form' %>
<br />
<br />
<%= link_to t('general.back'), applications_path %>

app/views/applications/show.html.erb
<h1><%= @application.name.upcase %></h1>
<div class='model_info'>
  <b><%= t('applications.type') %>:</b>
  <%= @application.app_type %><br/>
  <b><%= t('general.last_api_check_at') %>:</b>
  <%= @application.last_checked_at.to_formatted_s(:long_ordinal) %><br/>
  <b><%= t('general.active') %>:</b>
  <%= @application.active? ? t('general.yes') : t('general.no') %><br/>
  <b><%= t('general.created_by') %>:</b>
  <%= @application.user.email %><br/>
  <b><%= t('general.created_on') %>:</b>
  <%= @application.created_at.to_formatted_s(:long_ordinal) %><br/><br/>
  <b><%= 'Attributes:' %></b>
  <div id='application_attributes'>
    <%= t('applications.version_command') %>:
    <%= @application.version_command ? @application.version_command : t('general.not_applicable ') %><br/>
    <%= t('applications.path') %>:
    <%= @application.path ? @application.path : t('general.not_applicable ') %><br/>
    <%= t('applications.sends_emails') %>:
    <%= @application.sends_emails ? t('general.yes') : t('general.no') %><br/>
    <%= t('applications.major_application') %>:
    <%= @application.major_application? ? t('general.yes') : t('general.no') %><br/>
  </div><br/><br/><br/>
  <h3><%= t('servers.servers') %>:</h3>
  <%= render 'servers/servers', :servers => @application.servers %>
  <br />
  <br />
  <h3><%= t('application_families.application_families') %></h3>
  <%= render 'application_families/application_families', :application_families => @application.application_families %>
</div>
<br/><br/><br/>
<%= link_to t('general.back'), applications_path %>
<% if user_signed_in? %>
    | <%= link_to t('general.edit'), edit_application_path(@application) %>
<% end %>