config/routes.rb
Appinfo::Application.routes.draw do
  root :to => 'servers#index'

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => 'users/omniauth_callbacks'}

  namespace :admin do
    match '/' => 'admin#index'
    resources :users
  end

  resources :applications
  resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /html|csv/
  resources :token_authentications, :only => [:create, :destroy]
  resources :application_versions
  resources :server_relationships
  resources :server_databases
  resources :databases
  resources :application_families
  resources :application_family_applications
  resources :server_applications
  resource :user, only: [:show]

  namespace :api, :defaults => {:format => :html} do
    root :to => 'api#index'

    resources :api, :controller => :api

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: false), :defaults => {:format => :json} do
      resources :application_versions do
        collection do
          get :exists
        end
      end
      resources :applications do
        resources :application_versions
        collection do
          get :exists
        end
      end
      resources :servers, :id => /[\w.]+?/  do
        resources :application_versions
        resources :applications
        put :associate_application
        get :has_application
      end
      resources :server_relationships do
        collection do
          get :exists
        end
      end
      resources :server_databases do
        collection do
          get :exists
        end
      end
      resources :databases do
        collection do
          get :exists
        end
      end
      resources :application_families
      resources :application_family_applications do
        collection do
          get :exists
        end
      end
      resources :server_applications do
        collection do
          get :exists
        end
      end
    end

    scope module: :v2, constraints: ApiConstraints.new(version: 2, default: true), :defaults => {:format => :json} do
      resources :applications, :id => /[\w\d%\-]+?/ do
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :only => [:index, :show], :format => /json|csv|xml|yaml/ do
          resource :application_version
        end
        resources :databases, :id => /[\w\d%\-]+?/
        resources :server_applications, :only => [:index, :show]
      end
      resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/ do
        resources :applications, :id => /[\w\d%\-]+?/  do
          resource :application_version
          resources :server_applications
        end
        resources :server_applications do
          resource :application_version
        end
        resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
          resources :server_databases
        end
        resources :servers, :id => /[A-Za-z0-9\.]+?/, :format => /json/
        resources :server_relationships
        resources :server_databases
      end
      resources :databases, :only => [:index, :show], :id => /[\w\d%\-]+?/ do
        resource :application, :id => /[\w\d%\-]+?/
        resources :server_databases, :only => [:index, :show]
      end
      resources :application_families do
        resources :application_family_applications
      end
      resources :application_versions, :only => [:index, :show]
      resources :server_applications, :only => [:index, :show]
      resources :server_databases, :only => [:index, :show]
      resources :server_relationships, :only => [:index, :show]
      resources :application_family_applications, :only => [:index, :show]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :secure => false

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :confirmable, :lockable,
         :timeoutable

  devise :omniauthable, :omniauth_providers => [:auth_man]

  has_many :servers, :order => 'name ASC'
  has_many :applications, :order => 'name ASC'
  has_many :application_families, :order => 'name ASC'
  has_many :application_versions
  has_many :server_applications

  has_and_belongs_to_many :roles

  after_create :create_token, :assign_roles

  attr_accessible :email, :password, :password_confirmation, :remember_me, :authentication_token, :role_ids, :time_zone, :fname, :lname

  def role?(role)
    !!self.roles.find_by_name(role.to_s.downcase)
  end

  def self.from_omniauth(auth)
    user_return = where(provider: auth.provider, uid: auth.uid).first

    unless user_return
      user = User.new(
          :email        => auth.info.email,
          :password     => Devise.friendly_token[0,20],
          :fname        => auth.info.fname,
          :lname        => auth.info.lname,
          :time_zone    => auth.info.time_zone,
      )

      user.uid      = auth.uid
      user.provider = auth.provider

      user.skip_confirmation!
      user.save

      user_return = user
    end

    user_return.sync_with_omniauth(auth)

    user_return
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.auth_man_data'] && session['devise.auth_man_data']['extra']['raw_info']
        user.email      = data['email'] if user.email.blank?
        user.fname      = data['fname'] if user.fname.blank?
        user.lname      = data['lname'] if user.lname.blank?
        user.time_zone  = data['time_zone'] if user.time_zone.blank?
      end
    end
  end

  def sync_with_omniauth(auth)
    unless auth.info.fname == self.fname && auth.info.lname == self.lname && auth.info.time_zone == self.time_zone
      self.fname      = auth.info.fname
      self.lname      = auth.info.lname
      self.time_zone  = auth.info.time_zone

      self.save
    end
  end

  def full_name
    "#{self.fname} #{self.lname}"
  end

  def full_name_comma
    "#{self.lname}, #{self.fname}"
  end

  private
  def create_token
    self.reset_authentication_token!
  end

  def assign_roles
    self.roles << Role.find_by_name(:normal)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = t('users.created_user')
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    if @user.update_attributes(params[:user])
      flash[:notice] = t('users.updated_user')
      redirect_to admin_users_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = t('users.deleted_user')
      redirect_to admin_users_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def auth_man
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      session['devise_omniauth_myaccount'] = request.env['omniauth.auth'].info.my_account
      session['devise_omniauth_enable_gravatar'] = request.env['omniauth.auth'].info.enable_gravatar
      session['devise_login_type'] = :omniauth

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'AuthMan') if is_navigational_format?
    else
      raise Exception.new('Failed to create or find user.')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :set_user

  def show
  end

  private
  def set_user
    @user = current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, :url => admin_user_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, t('errors.error')) %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %>
    </div>
    <div class="field"><%= f.label :password, "New password" %><br />
      <%= f.password_field :password, :autofocus => true %></div>
    <div class="field"><%= f.label :password_confirmation, "Confirm new password" %><br />
      <%= f.password_field :password_confirmation %></div>
    <div class="field">
      <%= f.label :token_authentication_key %><br />
      <div class="token"><%= @user.authentication_token.blank? ? t('users.empty_token') : @user.authentication_token %></div>
      <%= link_to t('users.generate_token'), token_authentications_path(:user_id => @user.id, :format => :js),
                  :method => :post, :remote => true, :id => t('users.generate_token_id') %>
      <%= link_to t('users.delete_token'), token_authentication_path(@user, :format => :js),
                  :method => :delete, :remote => true, :id => t('users.delete_token_id') %>
    </div>
    <div class="field">
      <%= f.label :roles %><br />
      <% for role in Role.all %>
          <%= check_box_tag 'user[role_ids][]', role.id,
                            @user.role_ids.include?(role.id), :id => dom_id(role) %>
          <%= label_tag dom_id(role), role.name, :class => t('general.check_box_label') %>
      <% end %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t('general.editing') % t('users.users') %></h1>

<%= render 'form' %>
<br />
<br />

<%= link_to t('general.show'), admin_user_path(@user) %> |
<%= link_to t('general.back'), admin_users_path %>

app/views/admin/users/index.html.erb
<h1><%= t('general.listing') % t('users.users') %></h1>

<table id='index_table' class='data_table'>
  <thead>
      <tr>
        <th><%= t('users.email_address') %></th>
        <th><%= t('users.administrator') %></th>
        <th><%= t('servers.servers') %></th>
        <th><%= t('applications.applications') %></th>
        <th><%= t('general.tables.actions') %></th>
      </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.email ? user.email : user.unconfirmed_email, admin_user_path(user) %></td>
        <td><%= user.role?(:admin) ? t('general.yes') : t('general.no') %></td>
        <td><%= user.servers.count %></td>
        <td><%= user.applications.count %></td>
        <td>
          <%= link_to t('general.edit'), edit_admin_user_path(user) %>
          <% if user != current_user %>
            <%= link_to t('general.destroy'), admin_user_path(user), :confirm => t('general.are_you_sure'), :method => :delete %></td>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<h1><%= @user.email ? @user.email.upcase : @user.unconfirmed_email.upcase %></h1>
<div class='model_info'>
  <h3><%= t('users.attributes') %>:</h3>
  <table id='user_attributes'>
    <tr>
      <td><%= t('users.confirmed_on') %></td>
      <td><%= @user.confirmed_at.to_formatted_s(:long_ordinal) %></td>
    </tr>
    <tr>
      <td><%= t('users.token_authentication_key') %></td>
      <td><%= @user.authentication_token %></td>
    </tr>
    <tr>
      <td><%= t('users.administrator') %></td>
      <td><%= @user.role?(:admin) ? t('general.yes') : t('general.no') %></td>
    </tr>
  </table>

  <br/><br/><br/>
  <b><%= t('servers.servers') %>:</b><br/>
  <% if @user.servers.count == 0 %>
      <i><%= t('users.no_servers') %></i>
  <% else %>
      <% @user.servers.each do |s| %>
          <%= link_to s.name, s %><br/>
      <% end %>
  <% end %>
  </b><br/><br/>
  <b><%= t('applications.applications') %>:</b><br/>
  <% if @user.applications.count == 0 %>
      <i><%= t('users.no_applications') %></i>
  <% else %>
      <% @user.applications.each do |a| %>
          <%= link_to a.name, a %><br/>
      <% end %>
  <% end %>
</div>
<br/><br/><br/>

<%= link_to t('general.back'), admin_users_path %>